name: printoo_whatsapp
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # HTTP client
  dio: ^5.4.0

  # cash
  hive_ce: ^2.19.3

  # QR code rendering
  qr_flutter: ^4.1.0
  pdfx: ^2.9.2
  shimmer: ^3.0.0
  path_provider: ^2.1.5
  window_manager: ^0.5.1
  cached_network_image: ^3.4.1
  socket_io_client: ^3.1.6
  fullscreen_image_viewer: ^1.2.0
  pdfrx: ^1.0.101

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9
  hive_ce_generator: 1.9.2

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
