// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:printoo_whatsapp/home/domain/entities/printer_shourtcut.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(PrinterShourtcutAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(PrinterShourtcutAdapter());
  }
}
